name: Swift

on: [push]

jobs:
  test:
    name: Test Swasm on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: YOCKOW/Action-setup-swift@master
        with:
          # The version of Swift.
          swift-version: '5.1.2'
    
      - name: Build on
        run: swift build
      - name: Run tests
        run: swift test --enable-test-discovery
