name: Swift

on: [push]

jobs:
  test:
    name: Build and Test Swasm on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Build on
        run: swift build -v
      - name: Run tests
        run: swift test -v
